<a href="https://colab.research.google.com/github/Alexis-Casanova/challenge-alura-store/blob/main/AluraStoreLatam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importación de datos

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359
...,...,...,...,...,...,...,...,...,...,...,...,...
2354,Iphone 15,Electrónicos,1284400.0,66600.0,15/11/2021,Izabela de León,Medellín,1,Nequi,1,6.25184,-75.56359
2355,Impresora,Electrónicos,282800.0,15300.0,18/03/2023,Lucas Olivera,Bogotá,5,Nequi,1,4.60971,-74.08175
2356,Juego de mesa,Juguetes,122900.0,7200.0,06/07/2021,Lucas Olivera,Cali,5,Tarjeta de crédito,4,3.43722,-76.52250
2357,Cama box,Muebles,691300.0,35000.0,02/05/2022,Pedro Gomez,Pasto,1,Tarjeta de crédito,2,1.21361,-77.28111
2358,Smartwatch,Electrónicos,195000.0,8600.0,18/06/2022,Felipe Santos,Cali,4,Tarjeta de crédito,1,3.43722,-76.52250

#1. Análisis de facturación

In [2]:
tienda['Tienda'] = 'Tienda 1'
tienda2['Tienda'] = 'Tienda 2'
tienda3['Tienda'] = 'Tienda 3'
tienda4['Tienda'] = 'Tienda 4'

df_total = pd.concat([tienda, tienda2, tienda3, tienda4], ignore_index=True)

In [3]:
tiendaIngresoTotal = df_total.groupby('Tienda')['Precio'].sum()
print(tiendaIngresoTotal)
print("---")

tiendaIngresoNeto = df_total.groupby('Tienda')['Precio'].sum() - df_total.groupby('Tienda')['Costo de envío'].sum()
print(tiendaIngresoNeto)

Tienda
Tienda 1    1.150880e+09
Tienda 2    1.116344e+09
Tienda 3    1.098020e+09
Tienda 4    1.038376e+09
Name: Precio, dtype: float64
---
Tienda
Tienda 1    1.089502e+09
Tienda 2    1.056858e+09
Tienda 3    1.039503e+09
Tienda 4    9.830583e+08
dtype: float64

# 2. Ventas por categoría

In [16]:
ventas_por_categoria = df_total.groupby(['Tienda', 'Categoría del Producto']).size().reset_index(name='Cantidad Vendida')

ventas_por_categoria = ventas_por_categoria.sort_values(by=['Tienda', 'Cantidad Vendida'], ascending=[True, False])
ventas_por_categoria

      Tienda   Categoría del Producto  Cantidad Vendida
7   Tienda 1                  Muebles               465
3   Tienda 1             Electrónicos               448
5   Tienda 1                 Juguetes               324
2   Tienda 1        Electrodomésticos               312
1   Tienda 1     Deportes y diversión               284
4   Tienda 1   Instrumentos musicales               182
6   Tienda 1                   Libros               173
0   Tienda 1  Artículos para el hogar               171
15  Tienda 2                  Muebles               442
11  Tienda 2             Electrónicos               422
13  Tienda 2                 Juguetes               313
10  Tienda 2        Electrodomésticos               305
9   Tienda 2     Deportes y diversión               275
12  Tienda 2   Instrumentos musicales               224
14  Tienda 2                   Libros               197
8   Tienda 2  Artículos para el hogar               181
23  Tienda 3                  Muebles               499
19  Tienda 3             Electrónicos               451
21  Tienda 3                 Juguetes               315
18  Tienda 3        Electrodomésticos               278
17  Tienda 3     Deportes y diversión               277
22  Tienda 3                   Libros               185
16  Tienda 3  Artículos para el hogar               177
20  Tienda 3   Instrumentos musicales               177
31  Tienda 4                  Muebles               480
27  Tienda 4             Electrónicos               451
29  Tienda 4                 Juguetes               338
25  Tienda 4     Deportes y diversión               277
26  Tienda 4        Electrodomésticos               254
24  Tienda 4  Artículos para el hogar               201
30  Tienda 4                   Libros               187
28  Tienda 4   Instrumentos musicales               170

# 3. Calificación promedio de la tienda

In [5]:
calificacion_por_tienda = df_total.groupby('Tienda')['Calificación'].mean().reset_index()

calificacion_por_tienda = calificacion_por_tienda.sort_values(by='Calificación', ascending=False)
calificacion_por_tienda

     Tienda  Calificación
2  Tienda 3      4.048326
1  Tienda 2      4.037304
3  Tienda 4      3.995759
0  Tienda 1      3.976685

# 4. Productos más y menos vendidos

In [8]:
ventas_productos = df_total.groupby(['Tienda', 'Producto']).size().reset_index(name='Cantidad')

mas_vendidos = ventas_productos.loc[ventas_productos.groupby('Tienda')['Cantidad'].idxmax()]

menos_vendidos = ventas_productos.loc[ventas_productos.groupby('Tienda')['Cantidad'].idxmin()]

print("--- Productos Más Vendidos por Tienda ---")
print(mas_vendidos)
print("\n--- Productos Menos Vendidos por Tienda ---")
print(menos_vendidos)

--- Productos Más Vendidos por Tienda ---
       Tienda                   Producto  Cantidad
1    Tienda 1                    Armario        60
75   Tienda 2  Iniciando en programación        65
129  Tienda 3              Kit de bancas        57
163  Tienda 4                   Cama box        62

--- Productos Menos Vendidos por Tienda ---
       Tienda                   Producto  Cantidad
4    Tienda 1  Auriculares con micrófono        33
77   Tienda 2              Juego de mesa        32
111  Tienda 3    Bloques de construcción        35
175  Tienda 4         Guitarra eléctrica        33

# 5. Envío promedio por tienda

In [13]:
envio_promedio = df_total.groupby('Tienda')['Costo de envío'].mean().reset_index()

envio_promedio = envio_promedio.sort_values(by='Costo de envío', ascending=False)

print("Costo de Envío Promedio pagado por el cliente:")
print(envio_promedio)

Costo de Envío Promedio pagado por el cliente:
     Tienda  Costo de envío
0  Tienda 1    26018.609580
1  Tienda 2    25216.235693
2  Tienda 3    24805.680373
3  Tienda 4    23459.457167